### ISSUE TITLE
Clicking down arrow key on closed menu should highlight the first item

### ISSUE THREAD

**Issue by kentcdodds** [paypal/react-autocompletely#31]
[Here's an example](https://codesandbox.io/s/1jZV9Q9X0):

![down](https://user-images.githubusercontent.com/1500684/28656296-0271012a-7256-11e7-9953-a90ac833a007.gif)

@souporserious, I think this may have happened with your recent changes. Could you give it a look? Thanks!

**Comment by karanjthakkar** [comment]
@kentcdodds I was unable to reproduce that behavior on the same example. Here's a gif:

![kapture 2017-07-27 at 12 22 21](https://user-images.githubusercontent.com/1824298/28657821-4fbba85c-72c6-11e7-9741-9f30a45e3191.gif)

Is there a specific interaction after which this starts happening?

**Comment by kentcdodds** [comment]
The behavior only happens when you're focused on the input and you click the down arrow key on your keyboard :)

**Comment by karanjthakkar** [comment]
Ahh, the issue title confused me into thinking that this was related to clicking down arrow in the input and not the down arrow keyboard key :)

**Comment by souporserious** [comment]
Oops, yes I will look into this today 😅
