### ISSUE TITLE
Favor Array.prototype.filter() instead of Array.prototype.splice() when unmounting Item instances from the menu component

### ISSUE THREAD

**Issue by mstaicu** [paypal/react-autocompletely#34]
Problem description:

I've been following the streaming of the **react-autocompletely** and I've noticed some inconsistent behavior (on my re-implementation) when the Item components were unmounting, due to user interaction with the input element. 

The [removeItemInstance](https://github.com/paypal/react-autocompletely/blob/master/src/menu.js#L99) function on the Menu component, which uses ```Array.prototype.splice()```, modifies the array in a non-deterministic way.

Suggested solution:

I propose on using Array.prototype.filter()

```
removeItemInstance(itemInstance) {
  const index = this.items.indexOf(itemInstance)
  if (index !== -1) {
    this.items = this.items.filter(function(item, itemIndex) {
      return itemIndex !== index;
    });
  }
}
```

Thank you! 🙌🏻

Edit: It seems that the problem is not with ```splice``` but with the way the Items are being rendered.

**Comment by kentcdodds** [comment]
Hmmm... I'm unsure what problem this causes. Also unsure that it's still a problem.... Could you verify that it's still an issue and demonstrate what the issue is?

**Comment by mstaicu** [comment]
Most likely it was a cache issue, because it worked for a while using the ```.filter``` approach and then it went back to the old behavior. 

The problem was that the highlighted item, in the Menu, was not correctly selected when the user interacted with it via the Enter keydown event. 
If you were searching for something, and you were getting for example two results, and then you were deleting your input, those previous results were at the top of the items array, followed by the other items in the array.

I've looked ahead your implementation and noticed that you make use of a prop called ```index``` on the ```AutoComplete.Item``` so that fixed my problem as well.

All is well now 🙏🏻

**Comment by kentcdodds** [comment]
Haha, yeah, that's what I thought. I was pretty sure that I found that bug and fixed it :wink:

#spoileralert
