### ISSUE TITLE
Expose MenuStatus.getA11yStatusMessage

### ISSUE THREAD

**Issue by kentcdodds** [paypal/react-autocompletely#37]
Right now the `Menu` component uses `MenuStatus` and doesn't pass `getA11yStatusMessage`. We should probably allow people to pass `getA11yStatusMessage` to `Menu` and have that forward to the rendered `MenuStatus`.

This should be quite simple for anyone used to React. Especially since we don't actually have any tests yet 😅

**Comment by kentcdodds** [comment]
Oh, and we'll want to make sure we document this prop on the `Menu`

**Comment by kentcdodds** [comment]
This is related to #36 :)

**Comment by bernard-lin** [comment]
I'll do this tonight 🙂
