### ISSUE TITLE
Discussion - Consider to move all example into separated projects

### ISSUE THREAD

**Issue by nndung179** [paypal/react-autocompletely#59]
Currently, the examples are in 1 project. It is not flexible if we use many libs. For example, I saw some examples currently are using `glamorous `. What if I want to use `styled-components` or `material-ui`. So I suggest to consider to split examples to different projects.

**Comment by kentcdodds** [comment]
Thanks! We're actually going to have most of the examples be in codesandbox. See #1 👍
